### ISSUE TITLE
"About <speaker name> section shouldn't appear if there is no bio provided

### ISSUE THREAD

**Issue by heymosef** [CivicTechTO/women-and-color-frontend#79] opened 2018-03-14 04:37 UTC
## Expected Behaviour
Whole "About <speaker name" section shouldn't show up if the speaker hasn't entered anything for their bio. Currently it says “No description provided”.

## Work Needed
* [ ] Works on mobile
* [ ] Works on desktop
* [ ] Wrote some tests

**Comment by MattGiesa** [comment] 2018-03-18 23:15
duplicate of #83

**Closed by MattGiesa** 2018-03-18 23:15 UTC
Labels: enhancement
