### ISSUE TITLE
 Change scheme of “<person name>, <company name>” to “<person name> at <company name>” on the home page

### ISSUE THREAD

**Issue by heymosef** [CivicTechTO/women-and-color-frontend#81] opened 2018-03-14 04:40 UTC
## Design
[Link to Invision](https://projects.invisionapp.com/share/YJCPM4TQ6/#/screens/245103730)

## Work Needed
* [ ] Works on mobile
* [ ] Works on desktop
* [ ] Wrote some tests

**Comment by MattGiesa** [comment] 2018-03-18 23:03
duplicate of #85 which has more detail

**Closed by MattGiesa** 2018-03-18 23:03 UTC
Labels: enhancement
